services:
  reader:
    environment:
      STREAM_SERVER: ${LOCAL_STREAM_SERVER:-http://host.docker.internal:3005}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${READER_PORT:-3000}:3000"
